version: 2

models:
  - name: stg_sales
    description: "Staging model containing retail sales data in long format"

    columns:
      - name: id
        description: "Product identifier"
        tests:
          - not_null

      - name: item_id
        description: "Item identifier"
        tests:
          - not_null

      - name: store_id
        description: "Store identifier"
        tests:
          - not_null

      - name: d
        description: "Day identifier"
        tests:
          - not_null

      - name: sales
        description: "Daily sales quantity"
        tests:
          - not_null